src/components/MultiSelect/index.js, storybook/stories/form/MultiSelect/descriptions/multiSelect.js
Добавил недостающее свойство `display`
=> Фикс свойства `display` в мультиселекте

package.json, src/components/MultiSelect/index.js, storybook/stories/form/MultiSelect/descriptions/multiSelect.js
Добавление пропса filterBy для именованного поиска в строке поиска
=> add prime native filterBy props to MultiSelect

package.json, yarn.lock
- Обновил primereact
- Обновил primeflex
- Обновил primeicon
=> update: primereact, primeflex, primeicon

package.json, src/index.js
=> feat: added prime api

package.json, src/index.js
Added export of component Image
=> feat: added export of component Image

package.json, src/components/Spinner/index.js, src/index.js, src/index.scss
- Added `Spinner` component
- Added `.gap-N` styles
=> Spinner & gaps

package.json, src/components/Money/index.js, src/components/Number/index.js, src/components/Pagination/index.js, src/components/Pagination/style.scss, src/index.js, src/index.scss, yarn.lock
Added new components
- Money
- Number
- Pagination
=> New components (Money, Number & Pagination)

package.json, src/index.scss, src/styles/_layouts.scss, storybook/stories/form/Calendar/descriptions/datePicker.js, storybook/stories/form/Calendar/descriptions/dateTimePicker.js, storybook/stories/form/Calendar/descriptions/timePicker.js, storybook/stories/form/MultiSelect/descriptions/multiSelect.js
- Added combined styles for generating form layouts
=> Added layout styles

package.json, src/components/Pagination/index.js
Next/prev buttons are now available unless it's the first/last page
=> Pagination fix

package.json, src/components/MultiSelect/index.js, storybook/package.json, storybook/yarn.lock
- Checking for the display of the footer did not take into account the callback
- Storybook update sphere-ui package
=> Added function check for optionDisabled

package.json, src/components/DatePicker/index.js, src/components/DateTimePicker/index.js, src/components/TimePicker/index.js, src/index.scss, src/styles/_layouts.scss, storybook/i18n/locales/stories/datepicker/en.yml, storybook/i18n/locales/stories/datetimepicker/en.yml, storybook/i18n/locales/stories/timepicker/en.yml, storybook/package.json, storybook/stories/form/Calendar/descriptions/datePicker.js, storybook/stories/form/Calendar/descriptions/dateTimePicker.js, storybook/stories/form/Calendar/descriptions/timePicker.js, storybook/yarn.lock
* Added viewDate props
* Change theme
=> ViewDate props

.github/workflows/ci-deploy.yml, package.json
* Added config for sphere-ui deploying
=> Deploy sphere-ui in CI

.github/workflows/ci-deploy.yml, storybook/package.json, storybook/yarn.lock
* Added sass
* Changed deploy config
=> Fix storybok deploy

.github/workflows/ci-deploy.yml, package.json
* Fixed sphere-ui deploy config
=> Fixed deploy sphere

.github/workflows/ci-deploy.yml
* Added new rule for storybook publish
=> Fixed deploy storybook

.github/workflows/ci-deploy.yml, storybook/components/EventTable.js, storybook/components/Table.js, storybook/package.json, storybook/stories/gettingStarted/02-concept/constants.js, storybook/styles/global.scss, storybook/yarn.lock
* Fixed the version of the sphere in the storybook
* Fixed translates
=> Fixed storybook

src/components/BlockUI/index.js, src/index.js, storybook/i18n/locales/stories/blockui/en.yml, storybook/i18n/locales/stories/breadcrumb/en.yml, storybook/stories/display/BlockUI/blockUI.js, storybook/stories/display/BlockUI/blockui.stories.js
- added BlockUI component, based on Prime [component](https://www.primefaces.org/primereact/blockui/)
=> BlockUI component

package.json, src/components/MultiSelect/index.js, storybook/i18n/locales/stories/multiselect/en.yml, storybook/stories/form/MultiSelect/multiSelect.js
* added removeIcon property for multiselect
=> Added removeIcon props

.github/workflows/deploy-storybook.yml, storybook/package.json, storybook/yarn.lock
- Fix sphere-ui lib version
- Add workflow for storybook manual deploy
=> Fix storybook

package.json, src/components/DatePicker/index.js, src/components/DatePicker/style.scss, src/components/DatePicker/withRange.js, src/components/DateTimePicker/index.js, src/components/MultiSelect/index.js, src/components/Pagination/index.js, src/components/SelectButton/index.js, src/components/Spinner/index.js, src/index.scss, storybook/i18n/locales/stories/datepicker/en.yml, storybook/i18n/locales/stories/datetimepicker/en.yml, storybook/i18n/locales/stories/multiselect/en.yml, storybook/i18n/locales/stories/selectbutton/en.yml, storybook/i18n/locales/stories/spinner/en.yml, storybook/stories/display/Pagination/pagination.js, storybook/stories/display/Spinner/spinner.js, storybook/stories/form/DatePicker/datePicker.js, storybook/stories/form/DateTimePicker/dateTimePicker.js, storybook/stories/form/MultiSelect/multiSelect.js, storybook/stories/form/SelectButton/selectbutton.js
- add `name` property to SelectButton component
- add `dataKey` property to MultiSelect component #12 
- set `loading` property `true` by default in Spinner component #65
- add support for infinite pagination in Pagination component
- add some new properties to DatePicker, DateTimePicker components. Remove passing `locale` property.
- display range buttons on the right side of the calendar
=> Fix components

storybook/components/StoryPage.js, storybook/components/StoryPage.scss, storybook/i18n/locales/stories/layouts/en.yml, storybook/package.json, storybook/stories/form/InputText/inputtext.js, storybook/stories/layouts/Description/Description.js, storybook/stories/table/Datatable/Examples/Basic/basic.js, storybook/styles/global.scss, storybook/yarn.lock
Storybook updates:
- update `sphere-ui`
- update some stories
=> Storybook sphere-ui 4.6.2

storybook/i18n/locales/stories/datepicker/en.yml, storybook/i18n/locales/stories/datetimepicker/en.yml, storybook/package.json, storybook/stories/form/DatePicker/datePicker.js, storybook/stories/form/DateTimePicker/dateTimePicker.js, storybook/yarn.lock
- new sphere-ui version
- fix DatePicker, DateTimePicker stories
=> Storybook sphere-ui 4.6.3

package.json, src/components/DatePicker/constants.js, src/components/DatePicker/withRange.js, src/components/DateTimePicker/index.js, storybook/i18n/locales/stories/datepicker/en.yml, storybook/i18n/locales/stories/datetimepicker/en.yml, storybook/i18n/locales/stories/multiselect/en.yml, storybook/i18n/locales/stories/timepicker/en.yml, storybook/stories/form/DateTimePicker/dateTimePicker.js
- Fix #103 
- Show message about chosen date in UTC for DateTimePicker component #98 
- Update 30 days button text
=> Fix datepicker

package.json, src/components/Tree/index.js, src/index.js, storybook/i18n/locales/stories/tree/en.yml, storybook/stories/display/Tree/Documentation/documentation.js, storybook/stories/display/Tree/Documentation/documentation.stories.js, storybook/stories/display/Tree/Examples/DragDrop/dragdrop.js, storybook/stories/display/Tree/Examples/DragDrop/dragdrop.stories.js, storybook/stories/display/Tree/Examples/Events/events.js, storybook/stories/display/Tree/Examples/Events/events.stories.js, storybook/stories/display/Tree/Examples/Lazy/lazy.js, storybook/stories/display/Tree/Examples/Lazy/lazy.stories.js, storybook/stories/display/Tree/Examples/Selection/selection.js, storybook/stories/display/Tree/Examples/Selection/selection.stories.js, storybook/stories/display/Tree/Examples/Templating/templating.js, storybook/stories/display/Tree/Examples/Templating/templating.stories.js
=> Tree component

package.json, src/locales/index.js
Export Prime locale methods for changing default locale options. Locale options can be found here https://www.primefaces.org/primereact/locale/
=> Fix en locale calendar

storybook/components/StoryPage.js, storybook/package.json, storybook/yarn.lock
- Bump sphere-ui to 4.9.1 in storybook
- Fix first day of week for 'en' locale
=> Storybook: bump sphere-ui to 4.9.1

package.json, src/components/AutoComplete/index.js, src/components/Dropdown/index.js, src/components/MultiSelect/index.js, src/index.js, storybook/i18n/locales/stories/autocomplete/en.yml, storybook/i18n/locales/stories/dropdown/en.yml, storybook/i18n/locales/stories/multiselect/en.yml, storybook/stories/form/AutoComplete/autoComplete.js, storybook/stories/form/AutoComplete/autoComplete.stories.js, storybook/stories/form/Dropdown/dropdown.js, storybook/stories/form/MultiSelect/multiSelect.js
Add AutoComplete component
Add itemTemplate props in Dropdown component
Add onBlur props in MultiSelect component
=> Add AutoComplete component

storybook/package.json, storybook/yarn.lock
=> update sphere-ui in storybook (4.10.0)

storybook/package.json, storybook/yarn.lock
- Update `sphere-ui` version
-  #126
=> Storybook: bump sphere-ui version

package.json, src/components/Dropdown/index.js, storybook/i18n/locales/stories/dropdown/en.yml, storybook/stories/form/Dropdown/dropdown.js
=> Value template

package.json, src/components/DatePicker/index.js, src/components/DateTimePicker/index.js, src/utils/date.js, src/utils/index.js, storybook/stories/form/DatePicker/datePicker.js, storybook/stories/form/DateTimePicker/dateTimePicker.js
- Show next year in Datepicker
- Fix storybook
=> Fix datepicker year

package.json, yarn.lock
- Downgrade primereact version
=> bump version to 6.0.0-no-deps.1

package.json, src/components/DatePicker/withRange.js, src/utils/date.js, src/utils/index.js
- Updated patch version to 6.1.0-alpha.2
- Updated start date logic for range selection in DatePicker component
=> Updated range calendar

package.json, src/components/DatePicker/index.js, src/components/DatePicker/withRange.js, src/utils/date.js, src/utils/index.js
- Bump version
- Added the ability to change the start of the date with UTC format
=> Updated range calendar with UTC

package.json, rollup.config.js, src/components/DatePicker/style.scss, src/index.scss, src/styles/_layouts.scss, yarn.lock
=> Added theme support

src/components/DatePicker/constants.js, src/components/DatePicker/index.js, src/components/DatePicker/withRange.js, storybook/i18n/locales/stories/datepicker/en.yml, storybook/package.json, storybook/stories/form/DatePicker/datePicker.js, storybook/styles/global.scss, storybook/yarn.lock
- added new button preset "Last 24h" in Datepicker mode="range";
- added props for managing button presets.
=> Datepicker range buttons extension

package.json, src/components/Dropdown/index.js
- Fixed an issue where the filter input did not automatically receive focus when the dropdown panel was opened
- Implement dropdown collection management to ensure only one dropdown is open at a time
=> fix: focus filter input when dropdown panel opens
